index_save_path: "/home/jake/Datasets/saved_index"
index_load_path: ## "/home/jake/Datasets/saved_index"

index_type: "L2"

embed_model_provider: "openai"
embed_model_name: "text-embedding-3-small"

page_content_fields: ['title', 'description', 'tasks', 'requirements', 'points', 'work_description'] 
metadata_fields: ['career_type', 'career_min', 'career_max', 'work_type', 'education_type', 'workday_content', 'info_url']
